In [1]:
import pandas as pd

In [30]:
df = pd.read_csv("GCI_CompleteData4.csv")

In [31]:
df.size

30580

In [38]:
# df = df.loc[df['3rd_pillar_Macroeconomic_environment'] != None]
# df.size
missing = df[df['3rd_pillar_Macroeconomic_environment'].isnull()]
#.groupby(df['Country'])

In [41]:
missing['Country'].count

<bound method Series.count of 22                      Angola
23                      Angola
24                      Angola
27                      Angola
30                      Angola
31                      Angola
32                      Angola
118                   Barbados
120                   Barbados
132                     Belize
133                     Belize
134                     Belize
135                     Belize
137                     Belize
138                     Belize
139                     Belize
140                     Belize
141                     Belize
142                     Belize
150                      Benin
154                     Bhutan
155                     Bhutan
156                     Bhutan
157                     Bhutan
158                     Bhutan
159                     Bhutan
175                    Bolivia
183     Bosnia and Herzegovina
228               Burkina Faso
229               Burkina Faso
                 ...
1232              Sierra Leone
1233              Sierra Leone
1234              Sierra Leone
1235              Sierra Leone
1236              Sierra Leone
1298                  Suriname
1299                  Suriname
1300                  Suriname
1301                  Suriname
1306                  Suriname
1307                  Suriname
1308                  Suriname
1309                 Swaziland
1310                 Swaziland
1311                 Swaziland
1318                 Swaziland
1319                    Rwanda
1347                     Syria
1348                     Syria
1349                     Syria
1350                     Syria
1351                     Syria
1352                    Serbia
1359                Tajikistan
1402                   Tunisia
1496                     Yemen
1497                     Yemen
1498                     Yemen
1499                     Yemen
1504                     Yemen
Name: Country, Length: 114, dtype: object>

,Country,Year,1st_pillar_Institutions,2nd_pillar_Infrastructure,3rd_pillar_Macroeconomic_environment,4th_pillar_Health_and_primary_education,5th_pillar_Higher_education_and_training,6th_pillar_Goods_market_efficiency,7th_pillar_Labor_market_efficiency,8th_pillar_Financial_market_development,9th_pillar_Technological_readiness,10th_pillar_Market_size,11th_pillar_Business_sophistication_,12th_pillar_Innovation,Global_Competitiveness_Index,Population,GDP,Income group,Region,Forum classification
22,Angola,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19183907,6453,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
23,Angola,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19842251,7103,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
24,Angola,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20520103,7039,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
27,Angola,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22685632,7230,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
30,Angola,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25021974,7615,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa

In [45]:
df[df['3rd_pillar_Macroeconomic_environment'].isnull()]

,Country,Year,1st_pillar_Institutions,2nd_pillar_Infrastructure,3rd_pillar_Macroeconomic_environment,4th_pillar_Health_and_primary_education,5th_pillar_Higher_education_and_training,6th_pillar_Goods_market_efficiency,7th_pillar_Labor_market_efficiency,8th_pillar_Financial_market_development,9th_pillar_Technological_readiness,10th_pillar_Market_size,11th_pillar_Business_sophistication_,12th_pillar_Innovation,Global_Competitiveness_Index,Population,GDP,Income group,Region,Forum classification
22,Angola,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19183907,6453,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
23,Angola,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19842251,7103,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
24,Angola,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20520103,7039,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
27,Angola,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22685632,7230,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
30,Angola,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25021974,7615,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
31,Angola,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25334508,7039,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
32,Angola,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29784193,6887,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
118,Barbados,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,284215,12984,High income,Latin America and the Caribbean,Latin America and the Caribbean
120,Barbados,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,285719,12243,High income,Latin America and the Caribbean,Latin America and the Caribbean
132,Belize,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,298403,8240,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
133,Belize,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,306165,8293,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
134,Belize,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,313925,8145,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
135,Belize,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,321609,8209,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
137,Belize,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,336707,8287,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
138,Belize,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,344193,8215,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
139,Belize,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351706,8418,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
140,Belize,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,359287,8501,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
141,Belize,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,367329,7885,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
142,Belize,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,374681,7669,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
150,Benin,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10598482,1779,Low income,Sub-Saharan Africa,Sub-Saharan Africa
154,Bhutan,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,681471,5507,Lower middle income,Emerging and Developing Asia,South Asia
155,Bhutan,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,694990,5663,Lower middle income,Emerging and Developing Asia,South Asia
156,Bhutan,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,707830,5934,Lower middle income,Emerging and Developing Asia,South Asia
157,Bhutan,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,720246,6516,Lower middle income,Emerging and Developing Asia,South Asia
158,Bhutan,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,732246,6909,Lower middle income,Emerging and Developing Asia,South Asia
159,Bhutan,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,743711,7138,Lower middle income,Emerging and Developing Asia,South Asia
175,Bolivia,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11051600,5747,Lower middle income,Latin America and the Caribbean,Latin America and the Caribbean
183,Bosnia and Herzegovina,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3817554,9516,Upper middle income,Emerging and Developing Europe,Europe and North America
228,Burkina Faso,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18105570,1654,Low income,Sub-Saharan Africa,Sub-Saharan Africa
229,Burkina Faso,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18331897,1562,Low income,Sub-Saharan Africa,Sub-Saharan Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1232,Sierra Leone,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5391108,1249,Low income,Sub-Saharan Africa,Sub-Saharan Africa
1233,Sierra Leone,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5521838,1289,Low income,Sub-Saharan Africa,Sub-Saharan Africa
1234,Sierra Leone,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5647194,1304,Low income,Sub-Saharan Africa,Sub-Saharan Africa
1235,Sierra Leone,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5775902,1347,Low income,Sub-Saharan Africa,Sub-Saharan Africa
1236,Sierra Leone,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5908908,1400,Low income,Sub-Saharan Africa,Sub-Saharan Africa
1298,Suriname,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500953,13059,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
1299,Suriname,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,506657,13470,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
1300,Suriname,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,512522,13747,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
1301,Suriname,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,518141,14325,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
1306,Suriname,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,542975,17125,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
1307,Suriname,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,567076,16247,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
1308,Suriname,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,563402,16512,Upper middle income,Latin America and the Caribbean,Latin America and the Caribbean
1309,Swaziland,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1134853,5847,Lower middle income,Sub-Saharan Africa,Sub-Saharan Africa
1310,Swaziland,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1153750,5887,Lower middle income,Sub-Saharan Africa,Sub-Saharan Africa
1311,Swaziland,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1173529,5860,Lower middle income,Sub-Saharan Africa,Sub-Saharan Africa
1318,Swaziland,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1312783,5515,Lower middle income,Sub-Saharan Africa,Sub-Saharan Africa
1319,Rwanda,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1314789,5395,Lower middle income,Sub-Saharan Africa,Sub-Saharan Africa
1347,Syria,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19978756,6432,Lower middle income,"Middle East, North Africa, and Pakistan",Middle East and North Africa
1348,Syria,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19322593,5464,Lower middle income,"Middle East, North Africa, and Pakistan",Middle East and North Africa
1349,Syria,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18772481,5105,Lower middle income,"Middle East, North Africa, and Pakistan",Middle East and North Africa
1350,Syria,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18502413,4637,Lower middle income,"Middle East, North Africa, and Pakistan",Middle East and North Africa
1351,Syria,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19403558,4335,Lower middle income,"Middle East, North Africa, and Pakistan",Middle East and North Africa
1352,Serbia,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19400007,4300,Lower middle income,"Middle East, North Africa, and Pakistan",Middle East and North Africa
1359,Tajikistan,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8111894,2432,Lower middle income,Commonwealth of Independent States,Eurasia
1402,Tunisia,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10881450,10609,Lower middle income,"Middle East, North Africa, and Pakistan",Middle East and North Africa
1496,Yemen,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21701105,4354,Lower middle income,"Middle East, North Africa, and Pakistan",Middle East and North Africa
1497,Yemen,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22322699,4420,Lower middle income,"Middle East, North Africa, and Pakistan",Middle East and North Africa
1498,Yemen,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22954226,4494,Lower middle income,"Middle East, North Africa, and Pakistan",Middle East and North Africa
1499,Yemen,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23591972,4534,Lower middle income,"Middle East, North Africa, and Pakistan",Middle East and North Africa
1504,Yemen,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26832215,3887,Lower middle income,"Middle East, North Africa, and Pakistan",Middle East and North Africa

In [47]:
angola = df[df['Country']=='Angola']

In [49]:
minValue= None

for i in range(2007,2017):
    if angola[angola['Year']==i]['1st_pillar_Institutions'] ==Nan:

,Country,Year,1st_pillar_Institutions,2nd_pillar_Infrastructure,3rd_pillar_Macroeconomic_environment,4th_pillar_Health_and_primary_education,5th_pillar_Higher_education_and_training,6th_pillar_Goods_market_efficiency,7th_pillar_Labor_market_efficiency,8th_pillar_Financial_market_development,9th_pillar_Technological_readiness,10th_pillar_Market_size,11th_pillar_Business_sophistication_,12th_pillar_Innovation,Global_Competitiveness_Index,Population,GDP,Income group,Region,Forum classification
22,Angola,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19183907,6453,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
23,Angola,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19842251,7103,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
24,Angola,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20520103,7039,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
25,Angola,2010,3.219175,1.881551,3.614605,2.660120,2.125376,3.328692,4.218015,2.883372,2.592185,3.757473,2.641171,2.358215,2.934813,21219954,7047,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
26,Angola,2011,2.906737,1.887377,4.227984,2.887118,1.908271,3.214423,3.961234,2.672723,2.652359,3.834458,2.415584,2.052514,2.961498,21942296,7094,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
27,Angola,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22685632,7230,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
28,Angola,2013,2.759893,1.920763,5.026033,3.693878,2.066497,3.025866,3.655329,2.403806,2.470470,3.835517,2.888530,2.145923,3.147254,23448202,7488,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
29,Angola,2014,2.606999,2.014314,4.695090,3.539878,1.939449,2.922875,3.515020,2.499293,2.340303,3.836604,2.607472,2.117803,3.037738,24227524,7546,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
30,Angola,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25021974,7615,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
31,Angola,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25334508,7039,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
32,Angola,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29784193,6887,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa

In [62]:
angola[angola['Year']==2007]['1st_pillar_Institutions']

22   NaN
Name: 1st_pillar_Institutions, dtype: float64