In [10]:
import pandas as pd

In [52]:
df = pd.read_csv("GCI_CompleteData4.csv")
# df[df['Country']=='Angola']

In [53]:
df.loc[(df['Country']=='Angola') & (df["Year"] == 2010),'1st_pillar_Institutions']=float(df.loc[(df['Country']=='Angola') & (df["Year"] == 2011)]['1st_pillar_Institutions'])

df[df['Country']=='Angola']

,Country,Year,1st_pillar_Institutions,2nd_pillar_Infrastructure,3rd_pillar_Macroeconomic_environment,4th_pillar_Health_and_primary_education,5th_pillar_Higher_education_and_training,6th_pillar_Goods_market_efficiency,7th_pillar_Labor_market_efficiency,8th_pillar_Financial_market_development,9th_pillar_Technological_readiness,10th_pillar_Market_size,11th_pillar_Business_sophistication_,12th_pillar_Innovation,Global_Competitiveness_Index,Population,GDP,Income group,Region,Forum classification
22,Angola,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19183907,6453,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
23,Angola,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19842251,7103,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
24,Angola,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20520103,7039,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
25,Angola,2010,2.906737,1.881551,3.614605,2.660120,2.125376,3.328692,4.218015,2.883372,2.592185,3.757473,2.641171,2.358215,2.934813,21219954,7047,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
26,Angola,2011,2.906737,1.887377,4.227984,2.887118,1.908271,3.214423,3.961234,2.672723,2.652359,3.834458,2.415584,2.052514,2.961498,21942296,7094,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
27,Angola,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22685632,7230,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
28,Angola,2013,2.759893,1.920763,5.026033,3.693878,2.066497,3.025866,3.655329,2.403806,2.470470,3.835517,2.888530,2.145923,3.147254,23448202,7488,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
29,Angola,2014,2.606999,2.014314,4.695090,3.539878,1.939449,2.922875,3.515020,2.499293,2.340303,3.836604,2.607472,2.117803,3.037738,24227524,7546,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
30,Angola,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25021974,7615,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
31,Angola,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25334508,7039,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa
32,Angola,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29784193,6887,Upper middle income,Sub-Saharan Africa,Sub-Saharan Africa

In [54]:
# df = df.loc[df['3rd_pillar_Macroeconomic_environment'] != None]
# df.size
missing = df[df['3rd_pillar_Macroeconomic_environment'].isnull()]
#.groupby(df['Country'])

In [55]:
mylist = missing['Country'].unique()

In [56]:
df = pd.read_csv("GCI_CompleteData4.csv")
df[df['Country']=='Angola'].head(6)
print(missing['Country'].unique().size)

31

In [63]:
counter=0
# while(df['1st_pillar_Institutions'].isnull().any()):
    
for country in mylist:
    counter+=1
    print(counter,'/31')
    for i in range(2007,2016):

        if df[df['Country']==country][ df['Year']==i]['Global_Competitiveness_Index'].isnull().any() == True:
            print(country, i)
            df.loc[(df['Country']==country) & (df["Year"] == i),'1st_pillar_Institutions']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['1st_pillar_Institutions'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'2nd_pillar_Infrastructure']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['2nd_pillar_Infrastructure'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'3rd_pillar_Macroeconomic_environment']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['3rd_pillar_Macroeconomic_environment'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'4th_pillar_Health_and_primary_education']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['4th_pillar_Health_and_primary_education'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'5th_pillar_Higher_education_and_training']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['5th_pillar_Higher_education_and_training'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'6th_pillar_Goods_market_efficiency']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['6th_pillar_Goods_market_efficiency'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'7th_pillar_Labor_market_efficiency']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['7th_pillar_Labor_market_efficiency'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'8th_pillar_Financial_market_development']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['8th_pillar_Financial_market_development'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'9th_pillar_Technological_readiness']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['9th_pillar_Technological_readiness'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'10th_pillar_Market_size']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['10th_pillar_Market_size'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'11th_pillar_Business_sophistication_']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['11th_pillar_Business_sophistication_'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'12th_pillar_Innovation']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['12th_pillar_Innovation'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'Global_Competitiveness_Index']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['Global_Competitiveness_Index'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'GDP']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['GDP'])

1 /31
Angola 2015
2 /31
3 /31
Belize 2012

/Users/benjaminhowarth/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if __name__ == '__main__':

Belize 2013
Belize 2014
Belize 2015
4 /31
5 /31
6 /31
7 /31
8 /31
Burkina Faso 2015
9 /31
10 /31
11 /31
12 /31
13 /31
14 /31
15 /31
16 /31
17 /31
18 /31
19 /31
Libya 2015
20 /31
21 /31
22 /31
23 /31
24 /31
25 /31
Suriname 2015
26 /31
27 /31
Syria 2012
Syria 2013
Syria 2014
Syria 2015
28 /31
29 /31
30 /31
31 /31

In [73]:
for country in mylist:
    counter+=1
    print(counter,'/31')    
    
    for i in range(2017,2008,-1):

        if df[df['Country']==country][ df['Year']==i]['Global_Competitiveness_Index'].isnull().any() == True:
            print(country)
            df.loc[(df['Country']==country) & (df["Year"] == i),'1st_pillar_Institutions']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['1st_pillar_Institutions'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'2nd_pillar_Infrastructure']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['2nd_pillar_Infrastructure'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'3rd_pillar_Macroeconomic_environment']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['3rd_pillar_Macroeconomic_environment'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'4th_pillar_Health_and_primary_education']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['4th_pillar_Health_and_primary_education'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'5th_pillar_Higher_education_and_training']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['5th_pillar_Higher_education_and_training'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'6th_pillar_Goods_market_efficiency']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['6th_pillar_Goods_market_efficiency'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'7th_pillar_Labor_market_efficiency']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['7th_pillar_Labor_market_efficiency'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'8th_pillar_Financial_market_development']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['8th_pillar_Financial_market_development'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'9th_pillar_Technological_readiness']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['9th_pillar_Technological_readiness'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'10th_pillar_Market_size']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['10th_pillar_Market_size'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'11th_pillar_Business_sophistication_']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['11th_pillar_Business_sophistication_'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'12th_pillar_Innovation']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['12th_pillar_Innovation'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'Global_Competitiveness_Index']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['Global_Competitiveness_Index'])
            df.loc[(df['Country']==country) & (df["Year"] == i),'GDP']=float(df.loc[(df['Country']==country) & (df["Year"] == i-1)]['GDP'])

311 /31
312 /31
313 /31
314 /31
315 /31
316 /31
317 /31
318 /31
319 /31
320

/Users/benjaminhowarth/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  import sys

/31
321 /31
322 /31
323 /31
324 /31
325 /31
326 /31
327 /31
328 /31
329 /31
330 /31
331 /31
332 /31
333 /31
334 /31
335 /31
336 /31
337 /31
338 /31
339 /31
340 /31
341 /31

In [74]:
df.to_csv("GCI_CompleteData4_interpolated.csv")

In [26]:
# df[df['Country']=='Angola']
for country in mylist:
    for i in range(2017,2008,-1):
        print(i)
        
        if df[df['Country']==country][ df['Year']==i]['1st_pillar_Institutions'].isnull().any() == True:
            print(country)

2017
Angola
2016
Angola
2015
Angola
2014
2013
2012
2011
2010
2009
2017
Barbados
2016
2015
2014
2013
2012
2011
2010
2009
2017
Belize
2016
Belize
2015
Belize
2014
Belize
2013
Belize
2012
Belize
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017

/Users/benjaminhowarth/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

Bolivia
2016
2015
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
Burkina Faso
2016
Burkina Faso
2015
Burkina Faso
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
Gabon
2016
2015
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
2016
Guinea
2015
Guinea
2014
2013
2012
2011
2010
2009
2017
Guyana
2016
Guyana
2015
Guyana
2014
2013
2012
2011
2010
2009
2017
2016
Haiti
2015
Haiti
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
Libya
2016
Libya
2015
Libya
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
Rwanda
2016
2015
2014
2013
2012
2011
2010
2009
2017
2016
Seychelles
2015
Seychelles
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
Suriname
2016
Suriname
2015
Suriname
2014
2013
2012
2011
2010
2009
2017
2016
Swaziland
2015
Swaziland
2014
2013
2012
2011
2010
2009
2017
2016
Syria
2015
Syria
2014
Syria
2013
Syria
2012
Syria
2011
2010
2009
2017
Serbia
2016
2015
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009
2017
2016
2015
2014
2013
2012
2011
2010
2009

In [ ]:
#df[df['3rd_pillar_Macroeconomic_environment'].isnull()]

In [ ]:
# minValue= None

# for i in range(2007,2017):
#     if angola[angola['Year']==i]['1st_pillar_Institutions'] ==Nan:

In [ ]:
#angola[angola['Year']==2007]
# for i in range(2007,2016):
#     print(float(df.loc[(df['Country']=='Albania') & (df["Year"] == i+1)]['1st_pillar_Institutions']))

In [ ]:
for country in mylist:
    for i in range(2007,2016):
        if df[df['Country']==country][ df['Year']==i]['1st_pillar_Institutions'].isnull().any:
            df.loc[(df['Country']==country) & (df["Year"] == i),'1st_pillar_Institutions']=float(df.loc[(df['Country']==country) & (df["Year"] == i+1)]['1st_pillar_Institutions'])

In [ ]:
df.loc[(df['Country']=='Albania') & (df["Year"] == i)]['1st_pillar_Institutions']

In [ ]:
df[df['Country']=='Angola']

In [ ]:
df.Year.dtype

df.loc[df['Country']=='Albania'].Year[0]

In [ ]:
df.loc[(df['Country']=='Albania') & (df["Year"] == df.loc[df['Country']=='Albania'].Year[0])]

In [ ]:
df.loc[(df['Country']=='Albania') & (df["Year"] == 2007),'1st_pillar_Institutions']=2

In [ ]:
#df.loc[(df['column_name'] == some_value) & df['other_column'].isin(some_values)]
df.loc[(df['Country']=='Albania') & (df["Year"] == 2007)]['1st_pillar_Institutions']

In [ ]:
df.loc[df['Country']=='Angola']

In [ ]:
df[df['Country']=='Angola'][ df['Year']==2007] ['1st_pillar_Institutions']=10

In [ ]:
df[df['Country']=='Angola'][ df['Year']==2007] ['1st_pillar_Institutions']